language: python
python:
- '3.6'
install: true
script: echo "Deploying Janis-Runner"
deploy:
  provider: pypi
  user: illusional
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: PMCC-BioinformaticsCore/janis-assistant
  password:
    secure: qnFM6S0V59CunCMvJH5aO9MqVijTR2YxQ5l0nNyYXkVEjFEG2glJEiHGziU4WfDbhjIYGNqxoKia4GHd584xVOdR3X+9T0Gkjx0lcNA9diFdyc+VkP7kbs8sxPqYUeoy+sp/cF9sh/JqZB4gOFuN8JPRlWuZGE3PGpVT7/ZHL67UKFw6mjenkQH9/hqVbAE2PFrykWy7vUHtMkcrcFvtSBgm4+gbBGGJ7PbcfvbKiy/I9je/4er3EXGOYqjF4cv89EkQu6RdmARhgzbhnerlOs0zJtUNWYx0iFSE8D592E1lUqyDMy5ChoTaNIB0UeV8YbnH5IzBbvritv19/vzfFp01gVvb0H9YEi6YdiuZxyRKXGgPpmJETzGVf51WjxuwfooUCobJTCvMnYTSfjIAlAGpwl/BLGgqSRPIekkqCDXoUgfjgBfEW2U7wtYPPOiqPj5ms2sSo/6ScBjHax7kIhFsqNAAGMdPxG3iUNZWV558Wh/lph2o6QuKkLJD53Lv7mCT0NhyPs7KyDymhxVPyk5mV+yGfZYBKSY4zjOq/uFnFSdQX+SzkESvRA1jGuRZFBjH2c3eb82XnTVAC7Xy79ucKMU+74byQiObJQN2UKFrj48JrsoOkWXfWqpNS675hL2Azb7uf2LDR3832bMMZ72D+clJXV4/B71wVIANnb4=
