language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov coverage requests_mock nose_parameterized
script: nosetests -w janis_assistant --with-coverage --cover-package=janis_assistant
deploy:
  provider: pypi
  user: illusional
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: PMCC-BioinformaticsCore/janis-assistant
  password:
    secure: laLTrhzklU71XVaa43tS2CgWLXDMAZiDO/c/3lzShvVAoNK1xaQZMRs7iEmOTsfOP0rCXAmJwRdNLcY2pmQOu5g/ctFO75tbll5vZZ2KxlZZVAjqnRrWwg7YbkqNt2X5JvhsKHGQNah9zbajLVHQHN4hgQm3GnqT4hOlID6UMPZDksWU4VWBEZ/RZiCQfgIHN8c3vdJ8PSULoa0ImB+y9Jw8W+jH6hsTZgzUgNxVKjVzh+8OgDYPEhGHIHWV/VcpSo20EGkH0rCTK0NsSI+S8JWHlvSgJ0XycDIpGw7cr25JTJo70KrTkFNFOJXa/dQ0poNmZisDYfY/KobgKoL2S4tv/qF4m1D4nEVoiOI67cWeq7bNnxzdsQwSC+d21cHMDjqP1iMsRjMRDzFLa7j3OG6L6PyAO3KWNjnzpv9bbmfsycrc+EWs7CX4JfYq2caXbDWMxGnHr3MhdLVBecO9EaIDFUgo5glVORU+tPFBbFs59K4Xr+q8oKroKpX80IQDa9gBA0/bB+HJVkrG/Kfo7q8TaQ5VwRWoQaL8SNorCPxUNd1DYNWi/qm7+ifppRhVxYiDQCkcchb7WOznJqDhnFxm90VpDohLoNFnEprKxUL/pdEVDSJjDNhxrW9jhoIApz44PjJ9ZCjtud4maccKLfse18jYwyk6npfPBVpHeII=
